required: true
language: node_js
node_js:    
  - "14"

addons:
  chrome: stable

services:
  - docker

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - docker build -t rdb999/docker-ng -f Dockerfile.dev .

script:
  - docker run rdb999/docker-ng npm run all_tests
 
