required: true
language: node_js
node_js:    
  - "14"

addons:
  chrome: stable

services:
  - docker

before_install:
  - docker build -t rdb999/docker-ng -f Dockerfile.dev .

script:
  - docker run rdb999/docker-ng npm run all_tests
 
