#  build stage
# This line will tell the docker to pull the node image with tag 12.6.1-alpine if the images don't exist. 
# We are also giving a friendly name build to this image so we can refer it later.
FROM node:14-buster-slim AS builder

RUN apt-get update \
    && apt-get install -y --no-install-recommends chromium \
	&& apt-get -y install procps

ENV CHROME_BIN=/usr/bin/chromium
# ENV CHROME_BIN=/usr/bin/google-chrome

# This WORKDIR command will create the working directory in our docker image. 
# Going forward any command will be run in the context of this directory.
WORKDIR /app

# This COPY only package files
COPY package-lock.json package.json ./

# This RUN command will restore node_modules define in our package-lock.json
RUN npm ci

# This COPY command copies all the files from our current directory to the container working directory. this will copy all our source files.
COPY . .

# Default command to be executed when a container is created using this image
CMD ["npm", "run", "start"]
